version: "3"
services:
    app:
        image: prahadi/cmslara:${IMAGE_VER}
        container_name: cmslara
        restart: unless-stopped
        tty: true
        volumes:
            - .env:/var/www/.env
        networks:
            - doc-net

    nginx:
        image: prahadi/nginx
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8002:80"
        depends_on:
            - app
        networks:
            - doc-net

#Docker Networks
networks:
    doc-net:
        driver: bridge
