name: Deploy Application 

on:
  push:
    branches: ["staging"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: 103.175.219.114
          username: ${{ secrets.SERVER_USERNAME}}
          password: ${{ secrets.SERVER_PASSWORD}}
          port: ${{ secrets.SERVER_PORT  }}
          script: |
            whoami
            cd /var/www/html && ./.scripts/deploy.sh
            sudo git fetch origin staging:staging
            sudo git checkout staging
            sudo git pull origin staging
